services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

  api:
    build: .
    container_name: ia-corrector-api
    ports:
      - "8000:8000"
    environment:
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: llama3.1:8b
    depends_on:
      - ollama

volumes:
  ollama_models:
